#!/usr/bin/env bash
set -e
export OPSCLI_WORKDIR=$(cd $(dirname $0) && pwd)
# shellcheck source=common
. "$OPSCLI_WORKDIR/common"

cli_help() {
  cli_name=${0##*/}
  echo "
$cli_name
OPS  CLI
Version: $(cat $OPSCLI_WORKDIR/VERSION)
https://github.com/<???>

Usage: $cli_name [command]

Commands:
  hostname  Gives hostname
  get_logs  Download storage array logs
  *         Help
"
  exit 1
}

cli_log "Exporting config ..."
[ ! -f "$OPSCLI_WORKDIR/config" ] \
  && echo "ERROR: No $OPSCLI_WORKDIR/config file found. " \
  && echo "cp $OPSCLI_WORKDIR/config.template $OPSCLI_WORKDIR/config and adjust." \
  && exit 1

export $(cat "$OPSCLI_WORKDIR/config" | xargs)

case "$1" in
  hostname|h)
    "$OPSCLI_WORKDIR/commands/hostname"
    ;;
  get_logs|g)
    "$OPSCLI_WORKDIR/commands/get_logs"
    ;;
  *)
    cli_help
    ;;
esac
