#!/bin/bash

# Script to download logs from a specified ($IP) storage array.


# Take array name or IP as user input
echo -n "Enter array <hostname>c1 or IP address: " ; read IP ;

echo ""

# Check hostname / IP is in /etc/hosts file... i.e is accessable from FCGW
if grep -Fqw "$IP" /etc/hosts
then
    echo "Array / IP found"
else
    echo "Array / IP not found... Check /etc/hosts"
    exit
fi

echo ""

# Take password as user input
prompt="Enter manage password (stored in vault): "
unset password
while IFS= read -p "$prompt" -r -s -n 1 char
do
    if [[ $char == $'\0' ]]
    then
        break
    fi
    prompt='*'
    password+="$char"
done
echo
echo "Done."

echo ""

# Verify password is correct
if [ "$(sshpass -p $password ssh -tt -o ConnectTimeout=10 manage@masterary1c1 exit >/dev/null 2>&1; echo $?;)" -eq 0 ] ;

then

    echo "Password Accepted"

else

    echo "Password Failed"
    exit
fi

echo ""

# Take filename as user input, saves to /users/fcops/Downloads/<filename>
echo -n "Save as (filename.zip): " ; read FILENAME ;

echo ""

echo "#  #  #"

echo ""

#  Pipes into a screen here

HOST=$IP
export USER=manage
PASSWD=$password

screen -dm bash -c "ftp -n $HOST << EOT
binary
user $USER $PASSWD
prompt
get logs /users/fcops/Downloads/$FILENAME
bye
EOT"

echo "Logs are being downloading to -> /users/fcops/Downloads"

echo ""

echo "This operation will take ~10 minutes. Goodbye."
